n1=input('digite algo:')
print(type(n1))
print(' é alfanumerico ?' , n1.isalnum ())
print(n1.isascii())
print(n1.isdigit())
print(n1.isalpha())
print('Esta em minusculo?' , n1.islower())
print(n1.isdecimal())
print('è identificavel ?' , n1.isidentifier())
print('é numerico?' , n1.isnumeric())
print('Tem como printar?' , n1.isprintable())
print('Tem espaços?' , n1.isspace())
print('esta capitalizada? ' , n1.istitle())
print('Tem apenas maiusculos?' , n1.isupper())