nome = str(input('Digite seu nome completo: '))
lista = nome.split()
print('Seu nome é {}'.format(nome))
print('Seu primeiro nome é {}'.format(lista[0]))
print('E seu ultimo nome é {}'.format(lista[len(lista)-1]))
